### ISSUE TITLE
Class GoetasWebservices\Xsd\XsdToPhp\XMLSchema\DateTime does not exist

### ISSUE THREAD

**Issue by didulis** [goetas-webservices/xsd2php#94]
I managed to generate classes and metadata, but during deserialize I received error 

> Class GoetasWebservices\Xsd\XsdToPhp\XMLSchema\DateTime does not exist

In generated PHP Class the data type for object property is `\DateTime`, but in YAML mapping file for the same property there is `type: GoetasWebservices\Xsd\XsdToPhp\XMLSchema\DateTime`

After manually editing class name in YAML mapping file to `DateTime`, deserialization started to work as expected.

It would be nice if generator created equal class names in both files.

**Comment by goetas** [comment]
You forgot to register the custom type handlers as described in https://github.com/goetas-webservices/xsd2php#serialize--unserialize

They are responsible to handle the conversion of  `GoetasWebservices\Xsd\XsdToPhp\XMLSchema\DateTime` into PHP datetime objects

**Comment by erop** [comment]
> You forgot to register the custom type handlers as described in https://github.com/goetas-webservices/xsd2php#serialize--unserialize

Should I additionally register handlers for `jms/serializer-bundle`? I have the same issue while using JMS Serializer bundle as dependency in my own `symfony-bundle`.  I used it both as `--dev` dep in bundle source tree and as a prod dep in main app.

**Comment by nemozar** [comment]
Hi. Set handlers, but dos't work. Error: Class `GoetasWebservices\Xsd\XsdToPhp\XMLSchema\Date does not exist в файле /var/www/html/vendor/jms/metadata/src/Metadata/MetadataFactory.php на линии 151`

```
public function getJson()
    {
        $serializerBuilder = SerializerBuilder::create();
        $serializerBuilder->addMetadataDir($this->jms_dir, $this->namespace);
        $serializerBuilder->configureHandlers(function (HandlerRegistryInterface $handler) use ($serializerBuilder) {
            $serializerBuilder->addDefaultHandlers();
            $handler->registerSubscribingHandler(new BaseTypesHandler());
            $handler->registerSubscribingHandler(new XmlSchemaDateHandler());
        });
        $serializer = $serializerBuilder->build();
        return $serializer->serialize($this->object, 'json');
    }
```

stack trase

```
Код ошибки -1 : Class GoetasWebservices\Xsd\XsdToPhp\XMLSchema\Date does not exist в файле /var/www/html/vendor/jms/metadata/src/Metadata/MetadataFactory.php на линии 151#0 /var/www/html/vendor/jms/metadata/src/Metadata/MetadataFactory.php(151): ReflectionClass->__construct('GoetasWebservic...')
#1 /var/www/html/vendor/jms/metadata/src/Metadata/MetadataFactory.php(56): Metadata\MetadataFactory->getClassHierarchy('GoetasWebservic...')
#2 /var/www/html/vendor/jms/serializer/src/JMS/Serializer/GraphNavigator.php(193): Metadata\MetadataFactory->getMetadataForClass('GoetasWebservic...')
#3 /var/www/html/vendor/jms/serializer/src/JMS/Serializer/JsonSerializationVisitor.php(145): JMS\Serializer\GraphNavigator->accept(Object(DateTime), Array, Object(JMS\Serializer\SerializationContext))
#4 /var/www/html/vendor/jms/serializer/src/JMS/Serializer/GraphNavigator.php(248): JMS\Serializer\JsonSerializationVisitor->visitProperty(Object(JMS\Serializer\Metadata\PropertyMetadata), Object(app\modules\egrzags\services\RepeatCertService), Object(JMS\Serializer\SerializationContext))
#5 /var/www/html/vendor/jms/serializer/src/JMS/Serializer/Serializer.php(177): JMS\Serializer\GraphNavigator->accept(Object(app\modules\egrzags\services\RepeatCertService), Array, Object(JMS\Serializer\SerializationContext))
#6 /var/www/html/vendor/jms/serializer/src/JMS/Serializer/Serializer.php(96): JMS\Serializer\Serializer->visit(Object(JMS\Serializer\JsonSerializationVisitor), Object(JMS\Serializer\SerializationContext), Object(app\modules\egrzags\services\RepeatCertService), 'json', NULL)
#7 /var/www/html/vendor/phpoption/phpoption/src/PhpOption/Some.php(102): JMS\Serializer\Serializer->JMS\Serializer\{closure}(Object(JMS\Serializer\JsonSerializationVisitor))
#8 /var/www/html/vendor/jms/serializer/src/JMS/Serializer/Serializer.php(99): PhpOption\Some->map(Object(Closure))
#9 /var/www/html/base/XSDObject/XSD.php(73): JMS\Serializer\Serializer->serialize(Object(app\modules\egrzags\services\RepeatCertService), 'json')
```
